maintainer       "RightScale, Inc."
maintainer_email "razvan.tomescu@stratalux.com"
license          "Copyright Stratalux, Inc. All rights reserved."
description      "RightScale Database Manager"
long_description "RightScale Database Manager"
version          "1.0.0"
